### ISSUE TITLE
Missing build script

### ISSUE THREAD

**Issue by ghost** [MartiniMoe/MIDICtrl#1]
It looks like this is a multiproject build and you only published the actual "app" folder. There should be a `../settings.gradle` and `../build.gradle` in your local directory that are missing from this repo.

**Comment by MartiniMoe** [comment]
Thanks for your help!
I added the build script and was able to clone the repo on another machine and build the apk using gradle wrapper. So I hope this is ok now? :)

**Comment by ghost** [comment]
Thanks, works for me.
