### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [MartiniMoe/MIDICtrl#3]
You can add Screenshots for F-Droid, too, if you want. https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/ https://gitlab.com/snippets/1895688 That was simply information about what is still possible. You would then only have to enter the screenshots in fastlane.

**Comment by MartiniMoe** [comment]
Hi!
Thanks for your suggestion and especially the links with descriptions :) I already was thinking about adding screenshots and will do it soon!

**Comment by mondlicht-und-sterne** [comment]
I asked for the second link and added it in the hope that it would be better understood.
